const _csvData = {
  PI: [
    {eixo:'1. Relações Internacionais: conceitos básicos, atores, processos, instituições e paradigmas teóricos',topico:'Idealismo vs. Realismo',descricao:'Dos “14 Pontos” de Wilson ao caráter realista da ONU e seus agentes atuais.'},
    {eixo:'1. Relações Internacionais: conceitos básicos, atores, processos, instituições e paradigmas teóricos',topico:'Armadilha de Tucídides',descricao:'Aplicação ao relacionamento contemporâneo entre EUA e China.'},
    {eixo:'1. Relações Internacionais: conceitos básicos, atores, processos, instituições e paradigmas teóricos',topico:'Mackinder e o “Pivô Geográfico da História”',descricao:'Aplicação aos objetivos estratégicos atuais de EUA, China e Rússia.'},
    {eixo:'1. Relações Internacionais: conceitos básicos, atores, processos, instituições e paradigmas teóricos',topico:'Ordem e poder no mundo atual',descricao:'Disjunção entre ordem e poder diante de uma suposta crise sistêmica do ordenamento internacional.'},
    {eixo:'1. Relações Internacionais: conceitos básicos, atores, processos, instituições e paradigmas teóricos',topico:'Unipolaridade e multipolaridade',descricao:'A configuração do sistema internacional pós-Guerra Fria.'},
    {eixo:'2. A política externa brasileira: evolução desde 1945, principais vertentes e linhas de ação',topico:'Evolução 1945-1989',descricao:'Governos Dutra e Vargas ao regime militar e redemocratização com Sarney.'},
    {eixo:'2. A política externa brasileira: evolução desde 1945, principais vertentes e linhas de ação',topico:'Araújo Castro e o TNP',descricao:'O entendimento sobre o “congelamento do poder mundial” e a posição brasileira sobre o TNP.'},
    {eixo:'2. A política externa brasileira: evolução desde 1945, principais vertentes e linhas de ação',topico:'Pragmatismo Responsável e Ecumênico (governo Geisel)',descricao:'Antecedentes e principais linhas de ação.'},
    {eixo:'2. A política externa brasileira: evolução desde 1945, principais vertentes e linhas de ação',topico:'Joaquim Nabuco e a imagem externa do Brasil',descricao:'Visão sobre a “grandeza” de um país e o papel da diplomacia.'},
    {eixo:'2. A política externa brasileira: evolução desde 1945, principais vertentes e linhas de ação',topico:'Diplomacia pública brasileira',descricao:'Princípios e meios de aprimoramento.'},
    {eixo:'2. A política externa brasileira: evolução desde 1945, principais vertentes e linhas de ação',topico:'Idealismo como horizonte',descricao:'Desafios para conciliar interesses socioeconômicos com o idealismo na política externa.'},
    {eixo:'2. A política externa brasileira: evolução desde 1945, principais vertentes e linhas de ação',topico:'Continuidade e inovação',descricao:'Contrastes com a PEI (Política Externa Independente) e o Pragmatismo Responsável.'},
    {eixo:'2. A política externa brasileira: evolução desde 1945, principais vertentes e linhas de ação',topico:'Multilateralismo para o Brasil',descricao:'Importância e estratégias de fortalecimento dessa dimensão.'},
    {eixo:'2. A política externa brasileira: evolução desde 1945, principais vertentes e linhas de ação',topico:'Conferências de cúpula (pós-anos 90)',descricao:'Impacto nos objetivos estratégicos do Brasil.'},
    {eixo:'3. O Brasil e a América do Sul (Integração, MERCOSUL e iniciativas físicas/defesa)',topico:'Evolução do MERCOSUL e UNASUL',descricao:'Complementaridade na política externa atual.'},
    {eixo:'3. O Brasil e a América do Sul (Integração, MERCOSUL e iniciativas físicas/defesa)',topico:'Cláusula democrática do MERCOSUL',descricao:'Fundamentos, evolução e perspectivas.'},
    {eixo:'3. O Brasil e a América do Sul (Integração, MERCOSUL e iniciativas físicas/defesa)',topico:'MERCOSUL e novas parcerias internacionais do Brasil',descricao:'Papel e funcionalidade.'},
    {eixo:'3. O Brasil e a América do Sul (Integração, MERCOSUL e iniciativas físicas/defesa)',topico:'Multinacionais brasileiras na integração sul-americana',descricao:'Papel no processo de integração.'},
    {eixo:'3. O Brasil e a América do Sul (Integração, MERCOSUL e iniciativas físicas/defesa)',topico:'Iniciativas brasileiras na América do Sul',descricao:'Comunidade Sul-Americana de Nações e outras.'},
    {eixo:'3. O Brasil e a América do Sul (Integração, MERCOSUL e iniciativas físicas/defesa)',topico:'Tratado de Cooperação Amazônica (TCA)',descricao:'Importância para a integração regional.'},
    {eixo:'4. Argentina: política externa e relações com o Brasil',topico:'Relações bilaterais (1945-1980)',descricao:'Período de 1945 a 1980.'},
    {eixo:'4. Argentina: política externa e relações com o Brasil',topico:'Governo Mauricio Macri',descricao:'Política externa argentina e evolução das relações bilaterais e no MERCOSUL.'},
    {eixo:'4. Argentina: política externa e relações com o Brasil',topico:'Agenda bilateral diversificada',descricao:'Cooperação em reatores nucleares, indústria de defesa e integração física.'},
    {eixo:'4. Argentina: política externa e relações com o Brasil',topico:'Cooperação nuclear Brasil-Argentina',descricao:'Marcos institucionais.'},
    {eixo:'6. Estados Unidos da América: política externa e relações com o Brasil',topico:'Relações bilaterais Brasil-EUA',descricao:'Evolução recente e perspectivas.'},
    {eixo:'6. Estados Unidos da América: política externa e relações com o Brasil',topico:'Doutrina Bush e terrorismo',descricao:'Consequências no âmbito multilateral.'},
    {eixo:'6. Estados Unidos da América: política externa e relações com o Brasil',topico:'Relacionamento EUA-Irã',descricao:'Foco no programa nuclear iraniano.'},
    {eixo:'6. Estados Unidos da América: política externa e relações com o Brasil',topico:'Papel dos EUA na integração da Europa Ocidental',descricao:'Plano Marshall e Pacto Atlântico.'},
    {eixo:'7. União Europeia: origens, evolução, estrutura e relações com o Brasil',topico:'Desafios da integração europeia',descricao:'Marco de seus cinquenta anos.'},
    {eixo:'7. União Europeia: origens, evolução, estrutura e relações com o Brasil',topico:'Alargamento da UE',descricao:'Impactos para relações políticas e econômicas com o Brasil.'},
    {eixo:'7. União Europeia: origens, evolução, estrutura e relações com o Brasil',topico:'Trajetória da UE (mercado comum e moeda única)',descricao:'Perspectivas para relações com o MERCOSUL e o Brasil.'},
    {eixo:'8. Rússia: política externa e relações com o Brasil',topico:'(Abordagem transversal)',descricao:'Tratada em geopolítica e grupos como BRICS (sem questão discursiva exclusiva).'},
    {eixo:'9. África: política externa e relações com o Brasil',topico:'Relações Brasil-África',descricao:'Paradigma universalista desde anos 60, objetivos atuais e cooperação em defesa com Angola.'},
    {eixo:'9. África: política externa e relações com o Brasil',topico:'Política africana do Brasil nos anos 70',descricao:'Desafios diplomáticos para aproximação efetiva.'},
    {eixo:'9. África: política externa e relações com o Brasil',topico:'Governo Lula e a África',descricao:'Relevância do continente na política externa.'},
    {eixo:'10. O Brasil e a Ásia (China, Índia e Japão)',topico:'Ascensão da China',descricao:'Desafios e oportunidades para o Brasil (comercial, financeiro, ambiental).'},
    {eixo:'10. O Brasil e a Ásia (China, Índia e Japão)',topico:'Relações sino-japonesas',descricao:'Implicações para o sistema multilateral e as Nações Unidas.'},
    {eixo:'10. O Brasil e a Ásia (China, Índia e Japão)',topico:'Inserção regional da China (pós-anos 90)',descricao:'Variáveis envolvidas na “ascensão pacífica”.'},
    {eixo:'10. O Brasil e a Ásia (China, Índia e Japão)',topico:'Relação bilateral Brasil-China',descricao:'Sentido estratégico e diferentes dimensões.'},
    {eixo:'10. O Brasil e a Ásia (China, Índia e Japão)',topico:'Relações Brasil-Japão',descricao:'Comparação entre a década de 70 e o período atual (comércio, investimentos, vínculos humanos).'},
    {eixo:'11. O Brasil e o Oriente Médio',topico:'Relações Brasil-Líbano',descricao:'Linhas de ação e ajuda humanitária após explosão em Beirute (2020).'},
    {eixo:'11. O Brasil e o Oriente Médio',topico:'Brasil na UNIFIL (Força-Tarefa Marítima)',descricao:'Participação e prioridades em segurança marítima.'},
    {eixo:'11. O Brasil e o Oriente Médio',topico:'Conflito na Síria',descricao:'Tratamento internacional e funções do Conselho de Segurança da ONU.'},
    {eixo:'13.1 Multilateralismo universal (ONU e conferências)',topico:'Responsabilidade de Proteger (R2P)',descricao:'Surgimento, pilares e aplicação no caso da Líbia.'},
    {eixo:'13.1 Multilateralismo universal (ONU e conferências)',topico:'Diplomacia brasileira em negociações comerciais',descricao:'Participação em coalizões desde os anos 80.'},
    {eixo:'13.2 e 13.4 Desenvolvimento Sustentável e Meio Ambiente',topico:'Clima e desenvolvimento',descricao:'UNFCCC, Quioto, Acordo de Paris e papel do Brasil na COP30.'},
    {eixo:'13.2 e 13.4 Desenvolvimento Sustentável e Meio Ambiente',topico:'Mudanças climáticas no Ártico',descricao:'Impactos na exploração econômica e competição entre potências.'},
    {eixo:'13.2 e 13.4 Desenvolvimento Sustentável e Meio Ambiente',topico:'Desenvolvimento na agenda da ONU',descricao:'Posicionamento histórico da diplomacia brasileira.'},
    {eixo:'13.2 e 13.4 Desenvolvimento Sustentável e Meio Ambiente',topico:'Agenda pós-2015 (Rio+20)',descricao:'Integração de aspectos econômicos, sociais e ambientais.'},
    {eixo:'13.2 e 13.4 Desenvolvimento Sustentável e Meio Ambiente',topico:'Negociações sobre mudança do clima',descricao:'Evolução da posição brasileira (especialmente COP-15).'},
    {eixo:'13.2 e 13.4 Desenvolvimento Sustentável e Meio Ambiente',topico:'Biocombustíveis',descricao:'Importância para agendas de meio ambiente e combate à fome.'},
    {eixo:'13.5 Mar, espaço e Antártida',topico:'Amazônia Azul',descricao:'Interesses estratégicos no Atlântico Sul (ZOPACAS e PROSUB).'},
    {eixo:'13.5 Mar, espaço e Antártida',topico:'ZOPACAS',descricao:'Instrumento de promoção e defesa dos interesses brasileiros no Atlântico Sul.'},
    {eixo:'13.6 Direitos humanos e políticas de identidade',topico:'Agenda “Mulheres, Paz e Segurança”',descricao:'Resolução 1325 do CSNU e participação de mulheres brasileiras em missões de paz.'},
    {eixo:'13.6 Direitos humanos e políticas de identidade',topico:'Direitos humanos na diplomacia brasileira (anos 90)',descricao:'Conceito e condicionamento na ação externa.'},
    {eixo:'13.8 Comércio internacional e OMC',topico:'OMC pós-crise de 2008',descricao:'Protecionismo e proliferação de acordos regionais.'},
    {eixo:'13.8 Comércio internacional e OMC',topico:'Regionalismo comercial',descricao:'Adequação ao regime da OMC e o caso da Parceria Trans-Pacífico (TPP).'},
    {eixo:'13.8 Comércio internacional e OMC',topico:'Crise de 2008',descricao:'Impactos nas agendas financeira (G20) e comercial (Rodada Doha).'},
    {eixo:'13.9 Sistema financeiro internacional',topico:'Brasil e emergentes no G20 Financeiro',descricao:'Papel na reforma da arquitetura financeira global.'},
    {eixo:'13.10 Desarmamento e não proliferação',topico:'TPAN vs. TNP',descricao:'Razões da liderança brasileira na adoção do Tratado sobre a Proibição de Armas Nucleares.'},
    {eixo:'13.10 Desarmamento e não proliferação',topico:'Questão nuclear na política externa brasileira',descricao:'À luz da Estratégia Nacional de Defesa.'},
    {eixo:'13.10 Desarmamento e não proliferação',topico:'Não proliferação e terrorismo',descricao:'Regimes de não proliferação de ADM frente à ameaça do terrorismo.'},
    {eixo:'13.13 Narcotráfico, crime transnacional e cibernético',topico:'Internet e segurança cibernética',descricao:'Convenção de Budapeste e Estratégia Nacional de Segurança Cibernética (E-Ciber).'},
    {eixo:'13.13 Narcotráfico, crime transnacional e cibernético',topico:'Narcotráfico',descricao:'Participação brasileira na cooperação internacional (regional e global).'},
    {eixo:'13.14 Reforma das Nações Unidas',topico:'Reforma do Conselho de Segurança',descricao:'Conformação histórica, posição brasileira e atores envolvidos.'},
    {eixo:'13.15 Operações de paz das Nações Unidas',topico:'Brasil na FTM-UNIFIL',descricao:'Papel e histórico de participação.'},
    {eixo:'13.15 Operações de paz das Nações Unidas',topico:'Evolução histórica da participação brasileira',descricao:'Sete décadas e relação com documentos de defesa nacional.'},
    {eixo:'13.15 Operações de paz das Nações Unidas',topico:'Riscos e oportunidades das operações de paz',descricao:'Para a política externa brasileira.'},
    {eixo:'13.15 Operações de paz das Nações Unidas',topico:'Missão de paz no Haiti',descricao:'Motivações para o engajamento brasileiro.'},
    {eixo:'15. Formação de blocos econômicos e acordos comerciais',topico:'Adesão do Brasil à OCDE',descricao:'Caracterização, histórico desde anos 90 e benefícios.'},
    {eixo:'15. Formação de blocos econômicos e acordos comerciais',topico:'Grandes processos de negociação comercial',descricao:'Identificação e importância para o Brasil.'},
    {eixo:'16. A dimensão da segurança na política exterior do Brasil',topico:'Iniciativas no Atlântico Sul',descricao:'Paz, segurança e desenvolvimento (PND e PROSUB).'},
    {eixo:'16. A dimensão da segurança na política exterior do Brasil',topico:'Participação em missões de paz da ONU',descricao:'À luz da Estratégia Nacional de Defesa.'},
    {eixo:'17. Brasil e coalizões internacionais: G-20, IBAS e BRICS',topico:'Surgimento de novos atores',descricao:'Mudanças estruturais (Brasil, China, Índia) e mecanismos de coordenação financeira/comercial.'},
    {eixo:'17. Brasil e coalizões internacionais: G-20, IBAS e BRICS',topico:'BRIC/BRICS',descricao:'Definição e participação nos regimes globais de comércio, clima e segurança.'},
    {eixo:'17. Brasil e coalizões internacionais: G-20, IBAS e BRICS',topico:'Papel do Brasil em grupos Sul-Sul',descricao:'UNASUL, CELAC, BRICS, IBAS, AFRAS, ASPA.'},
    {eixo:'17. Brasil e coalizões internacionais: G-20, IBAS e BRICS',topico:'Aproximação com grandes países emergentes',descricao:'Interesses que orientam essa perspectiva.'},
    {eixo:'17. Brasil e coalizões internacionais: G-20, IBAS e BRICS',topico:'Iniciativas concertadas (início do governo Lula)',descricao:'Com China, Índia, Rússia e África do Sul.'},
    {eixo:'18. O Brasil e a cooperação Sul-Sul',topico:'Cooperação brasileira para o desenvolvimento',descricao:'Características, condicionantes e implicações (técnica e humanitária).'},
    {eixo:'18. O Brasil e a cooperação Sul-Sul',topico:'Cúpula América do Sul – Países Árabes (ASPA)',descricao:'Fundamentos da aproximação.'},
    {eixo:'Extras (temas transversais)',topico:'Disjunção entre ordem e poder',descricao:'Como crise sistêmica de transição na regulação econômica e política global.'},
    {eixo:'Extras (temas transversais)',topico:'O que define uma “grande potência”',descricao:'Ferramentas para um país “ser grande” no sistema internacional.'},
    {eixo:'Extras (temas transversais)',topico:'Impacto das conferências de cúpula',descricao:'Na agenda dos Chefes de Executivo e nas chancelarias desde os anos 90.'}
  ],
  DIP: [
    {eixo:'1. Normas jurídicas',topico:'Dicotomia do direito',descricao:'Análise da paulatina erosão da dicotomia do direito (summa divisio) e a moderna publicização do direito privado.'},
    {eixo:'2. Personalidade jurídica',topico:'Personalidade no DIP',descricao:'Discussão sobre o reconhecimento da personalidade jurídica no Direito Internacional Público entre a abstração e a realidade.'},
    {eixo:'4. Estado',topico:'Repartição de competências na Federação brasileira',descricao:'Competências enumeradas e concorrentes entre União, estados, DF e municípios.'},
    {eixo:'4. Estado',topico:'Soberania estatal',descricao:'Análise da soberania estatal: se absoluta ou relativa frente aos interesses da comunidade internacional.'},
    {eixo:'4. Estado',topico:'Soberania vs. livre comércio',descricao:'O conflito entre a soberania sobre recursos naturais e o livre comércio no âmbito da OMC.'},
    {eixo:'5. Estado Democrático de Direito',topico:'Separação de poderes',descricao:'A importância do princípio da separação de poderes no debate sobre o controle externo do Poder Judiciário.'},
    {eixo:'6. Organização e competências dos poderes no Brasil',topico:'Congresso Nacional e política externa',descricao:'Atuação da Câmara e do Senado, isolada e conjuntamente, na formulação e condução da política externa brasileira.'},
    {eixo:'7. Processo legislativo brasileiro',topico:'Rejeição de medidas provisórias',descricao:'Análise jurídica sobre a rejeição de MPs e a manutenção de relações jurídicas constituídas durante sua vigência (ex.: gratificações a diplomatas).'},
    {eixo:'7. Processo legislativo brasileiro',topico:'Trancamento de pauta por MP',descricao:'Sugestões de revogação, reedição ou declaração de inconstitucionalidade de MPs que trancam a pauta da Câmara dos Deputados.'},
    {eixo:'8. Direitos e garantias fundamentais',topico:'Absolutismo vs. relativização',descricao:'Análise sobre se os direitos fundamentais são absolutos ou comportam relativização e se pessoas jurídicas são beneficiárias desses direitos.'},
    {eixo:'8. Direitos e garantias fundamentais',topico:'Direitos/garantias individuais e instrumentos',descricao:'"Diferenciação entre direitos e garantias; identificação de instrumentos como mandado de segurança e habeas data."'},
    {eixo:'8. Direitos e garantias fundamentais',topico:'Pena de morte para estrangeiros',descricao:'Discussão sobre a viabilidade jurídica de emenda constitucional prevendo pena de morte para estrangeiros em casos de terrorismo.'},
    {eixo:'8. Direitos e garantias fundamentais',topico:'Ações afirmativas',descricao:'Análise jurídica das ações afirmativas sob a ótica do princípio da igualdade.'},
    {eixo:'9. Administração Pública no Brasil',topico:'Princípios da Administração Pública (Art. 37, CF/88)',descricao:'Identificação e explicação do conteúdo jurídico dos princípios que regem a Administração Pública.'},
    {eixo:'11. Responsabilidade civil do Estado',topico:'Pressupostos e espécies',descricao:'Responsabilidade objetiva e subjetiva e o princípio da dupla garantia.'},
    {eixo:'11. Responsabilidade civil do Estado',topico:'Danos por fenômenos naturais',descricao:'Análise da responsabilidade municipal em danos causados por deslizamentos em áreas de risco.'},
    {eixo:'15. Direito Internacional e Direito Interno',topico:'Relação entre Direito Constitucional e DIP',descricao:'Complementaridade e ações recíprocas entre o Direito Constitucional e o Direito Internacional.'},
    {eixo:'15. Direito Internacional e Direito Interno',topico:'Incorporação de tratados no Brasil',descricao:'Fases do processo de incorporação e o entendimento do STF sobre hierarquia.'},
    {eixo:'15. Direito Internacional e Direito Interno',topico:'Compromissos internacionais por governadores',descricao:'Validade de compromissos internacionais assumidos por governadores de estados-membros.'},
    {eixo:'16. Princípios das relações internacionais do Brasil (Art. 4º, CF/88)',topico:'Conteúdo normativo e exemplos',descricao:'Enumeração e análise reflexiva dos princípios do Art. 4º da CF/88, com exemplos históricos de sua incidência na política externa.'},
    {eixo:'16. Princípios das relações internacionais do Brasil (Art. 4º, CF/88)',topico:'Solução pacífica de controvérsias',descricao:'Relação entre a obrigação de solução pacífica de controvérsias e o texto constitucional brasileiro.'},
    {eixo:'17. DIP e Direito Internacional Privado (LINDB)',topico:'Princípios gerais do direito',descricao:'A função dos princípios gerais do direito no ordenamento jurídico à luz da LINDB.'},
    {eixo:'17. DIP e Direito Internacional Privado (LINDB)',topico:'Homologação de divórcio homoafetivo',descricao:'Possibilidade de homologação de sentença estrangeira de divórcio homoafetivo no Brasil.'},
    {eixo:'17. DIP e Direito Internacional Privado (LINDB)',topico:'Dívida de jogo contraída no exterior',descricao:'Análise da cobrança de dívida de jogo contraída no exterior e viabilidade de homologação da sentença estrangeira correspondente.'},
    {eixo:'18. Estado (surgimento, extinção, soberania, reconhecimento)',topico:'Desaparecimento de território por elevação do mar',descricao:'Impactos na existência do Estado nacional.'},
    {eixo:'18. Estado (surgimento, extinção, soberania, reconhecimento)',topico:'Reconhecimento da República brasileira (1889)',descricao:'O pedido de reconhecimento à luz das normas atuais de reconhecimento de Estado e governo.'},
    {eixo:'18. Estado (surgimento, extinção, soberania, reconhecimento)',topico:'Caso Lotus',descricao:'Análise da premissa de que limitações à independência dos Estados não se presumem.'},
    {eixo:'18. Estado (surgimento, extinção, soberania, reconhecimento)',topico:'Doutrinas Drago, Tobar e Estrada',descricao:'Importância para o direito das gentes.'},
    {eixo:'19. Território (formação do território brasileiro)',topico:'Tratados Brasil-Paraguai (1872-1975)',descricao:'Pressupostos da personalidade jurídica, critérios de delimitação territorial e aproveitamento hídrico.'},
    {eixo:'20. Povo (nacionalidade, estrangeiro, extradição, asilo)',topico:'Nacionalidade e apatridia',descricao:'Conceito de nacionalidade, formas de aquisição, perda e proteção aos apátridas no direito brasileiro e internacional.'},
    {eixo:'20. Povo (nacionalidade, estrangeiro, extradição, asilo)',topico:'Asilo vs. refúgio',descricao:'Diferenciação e o tratamento dado pela Lei de Migração em comparação ao antigo Estatuto do Estrangeiro.'},
    {eixo:'20. Povo (nacionalidade, estrangeiro, extradição, asilo)',topico:'Brasileiro processado por crime no exterior',descricao:'Possibilidade de brasileiro ser processado no Brasil por crime cometido no exterior.'},
    {eixo:'20. Povo (nacionalidade, estrangeiro, extradição, asilo)',topico:'Expulsão de estrangeiro com vínculos familiares',descricao:'Análise da legalidade da expulsão de estrangeiro com vínculos familiares e tempo de residência no Brasil.'},
    {eixo:'21. Jurisdição, imunidades, responsabilidade internacional',topico:'Imunidades diplomáticas e consulares',descricao:'Definição, propósitos e instrumentos convencionais que as regem.'},
    {eixo:'21. Jurisdição, imunidades, responsabilidade internacional',topico:'Responsabilidade por edição de lei interna',descricao:'A responsabilidade internacional do Estado pela mera edição de lei interna contrária a obrigações internacionais.'},
    {eixo:'21. Jurisdição, imunidades, responsabilidade internacional',topico:'Imunidade de organização internacional (ato de império vs. gestão)',descricao:'Decisão sobre imunidade de jurisdição em reclamações trabalhistas.'},
    {eixo:'23. Fontes do DIP',topico:'Tratados como fonte',descricao:'Importância dos tratados, princípios do livre consentimento, boa-fé e pacta sunt servanda.'},
    {eixo:'23. Fontes do DIP',topico:'Jus cogens',descricao:'Conceito e abrangência como ordem internacional superior e sua efetividade diante do uso da força.'},
    {eixo:'23. Fontes do DIP',topico:'Reservas a tratados',descricao:'Distinção de declaração interpretativa e efeitos de objeções às reservas.'},
    {eixo:'23. Fontes do DIP',topico:'Art. 38 do Estatuto da CIJ',descricao:'Análise se constitui enumeração exaustiva das fontes do DIP.'},
    {eixo:'24. Solução pacífica de controvérsias',topico:'Meios diplomáticos e jurisdicionais',descricao:'Bons ofícios, mediação, conciliação, arbitragem e CIJ.'},
    {eixo:'24. Solução pacífica de controvérsias',topico:'Jurisdição da CIJ',descricao:'Espécies (contenciosa e consultiva) e formas de fixação de competência.'},
    {eixo:'24. Solução pacífica de controvérsias',topico:'Pacto de Bogotá',descricao:'Importância para a resolução de controvérsias perante a CIJ.'},
    {eixo:'25. Organizações internacionais',topico:'"Carta da ONU como ""constituição internacional"""',descricao:'Debate sobre a primazia sobre outros tratados (Art. 103).'},
    {eixo:'25. Organizações internacionais',topico:'Limites ao poder do Conselho de Segurança',descricao:'Possibilidade de a CIJ invalidar suas resoluções.'},
    {eixo:'25. Organizações internacionais',topico:'Controle judicial brasileiro sobre resoluções do CS',descricao:'Controle sobre resoluções internalizadas por decreto.'},
    {eixo:'26. Direito da Integração Regional (MERCOSUL)',topico:'Desenvolvimento do MERCOSUL',descricao:'Tratado de Assunção e participação brasileira em sistemas de solução de controvérsias regionais.'},
    {eixo:'26. Direito da Integração Regional (MERCOSUL)',topico:'Modelos supranacional vs. intergovernamental',descricao:'Comparação entre União Europeia e MERCOSUL.'},
    {eixo:'27. Uso da força e segurança coletiva',topico:'Legítima defesa na Carta da ONU',descricao:'Condições para o exercício e controvérsias sobre legítima defesa preventiva.'},
    {eixo:'27. Uso da força e segurança coletiva',topico:'Armas nucleares',descricao:'Regulação da ameaça ou uso e pareceres da CIJ.'},
    {eixo:'28. Direito internacional dos direitos humanos',topico:'Sistema Interamericano de DH',descricao:'Papel da Comissão e da Corte IDH e relação do Brasil com o sistema.'},
    {eixo:'28. Direito internacional dos direitos humanos',topico:'Tratados de DH como emendas constitucionais',descricao:'Equivalência (Art. 5º, §3º da CF/88).'},
    {eixo:'29. Conflitos armados e Direito Humanitário / Refugiados',topico:'Convenções de Genebra e Protocolos',descricao:'Pedra angular do DIH.'},
    {eixo:'29. Conflitos armados e Direito Humanitário / Refugiados',topico:'Convergências entre DIH, DIDH e Direito dos Refugiados',descricao:'Pontos de contato e integração normativa.'},
    {eixo:'29. Conflitos armados e Direito Humanitário / Refugiados',topico:'Princípio do non-refoulement',descricao:'Proteção aos refugiados na legislação brasileira e internacional.'},
    {eixo:'30. Direito penal internacional',topico:'TPI e tribunais ad hoc',descricao:'Processo de criação, tribunais para Ex-Iugoslávia e Ruanda, princípio da complementaridade.'},
    {eixo:'30. Direito penal internacional',topico:'Crimes do Estatuto de Roma',descricao:'Espécies de crimes sob competência do TPI e responsabilidade do indivíduo vs. Estado.'},
    {eixo:'31. Direito do comércio internacional (OMC)',topico:'Sistema de solução de controvérsias da OMC',descricao:'"Eficácia exemplificada pelo ""Contencioso do Algodão""."'},
    {eixo:'31. Direito do comércio internacional (OMC)',topico:'Cláusula da nação mais favorecida e blocos regionais',descricao:'Conciliação entre a cláusula e a existência de blocos econômicos regionais.'},
    {eixo:'32. Meio Ambiente e Direito do Mar',topico:'Elevação do nível do mar e zonas marítimas',descricao:'Impactos nas delimitações à luz da CNUDM.'},
    {eixo:'32. Meio Ambiente e Direito do Mar',topico:'Direito Internacional e Água',descricao:'Dissertação geral sobre o tema em suas diversas dimensões.'},
    {eixo:'Extras (temas transversais)',topico:'Teoria e História do DIP',descricao:'Afirmação de que o DIP surgiu para erguer fronteiras e hoje se ocupa de derrubá-las.'},
    {eixo:'Extras (temas transversais)',topico:'Natureza jurídica do DIP',descricao:'Discussão se o DIP é um código de regras morais ou um sistema jurídico de coordenação eficaz.'},
    {eixo:'Extras (temas transversais)',topico:'"""Doutrina das Danaides"""',descricao:'Reflexão sobre o trabalho incessante dos internacionalistas em defender a existência e o esgotamento do tema do direito das gentes.'}
  ],
  ECO: [
    {eixo:'1. Microeconomia',topico:'1.1 Demanda do Consumidor',descricao:'- Aumento na quantidade procurada de brinquedos em festas de fim de ano sob a ótica de preferências racionais e restrição orçamentária.'},
    {eixo:'1. Microeconomia',topico:'1.2 Oferta do Produtor',descricao:'- Efeitos da distinção entre curto/longo prazo sobre a elasticidade-preço da oferta em concorrência perfeita.'},
    {eixo:'1. Microeconomia',topico:'1.3 Tipos de Mercados e de Bens',descricao:'- Comparação duopólio de Cournot vs. Stackelberg (preço, quantidade, bem-estar).'},
    {eixo:'2. Macroeconomia',topico:'2.1 Contabilidade Nacional',descricao:'- Cálculo de PIB, PNB, Renda Disponível Bruta e Poupança Bruta com dados reais do Brasil.'},
    {eixo:'2. Macroeconomia',topico:'2.2 Contas Externas',descricao:'- Análise da estrutura do Balanço de Pagamentos do Brasil e razões para aumento das reservas cambiais.'},
    {eixo:'2. Macroeconomia',topico:'2.3 Setor Público e Política Fiscal',descricao:'- Relação entre despesa de juros, resultado primário e dívida pública sob a LRF.'},
    {eixo:'2. Macroeconomia',topico:'2.4 Modelo IS-LM-BP',descricao:'- Efeitos do aumento das despesas fiscais no modelo IS-LM (economia fechada, mercado de moeda e taxa de juros).'},
    {eixo:'2. Macroeconomia',topico:'2.5 Teoria e Política Monetária',descricao:'- Definição de moeda, funções e processo de criação via multiplicador monetário.'},
    {eixo:'2. Macroeconomia',topico:'2.6 Política Monetária (instrumentos)',descricao:'- Funcionamento do Regime de Metas de Inflação, autonomia do BC e Regra de Taylor.'},
    {eixo:'2. Macroeconomia',topico:'2.8 Emprego e Renda',descricao:'- Definição de demanda e oferta de trabalho sob perspectiva neoclássica.'},
    {eixo:'3. Economia Internacional',topico:'3.1 Teorias de Comércio',descricao:'- Vantagem comparativa (Ricardiano e Heckscher-Ohlin) e explicação para comércio intrassetorial.'},
    {eixo:'3. Economia Internacional',topico:'3.2 Macroeconomia Aberta',descricao:'"- Determinantes da taxa de câmbio em regimes fixos/flutuantes (""câmbio sujo"") e papel das reservas."'},
    {eixo:'3. Economia Internacional',topico:'3.3 Política Comercial',descricao:'- Análise da cláusula de conteúdo local vs. tarifas e cotas.'},
    {eixo:'4. História Econômica Brasileira',topico:'4.1 Século XIX',descricao:'- Análise de Celso Furtado sobre o atraso industrial brasileiro no século XIX e impacto dos tratados com a Inglaterra.'},
    {eixo:'4. História Econômica Brasileira',topico:'4.2 Primeira República',descricao:'- Relação economia cafeeira, crises da Primeira República e incentivo à industrialização.'},
    {eixo:'4. História Econômica Brasileira',topico:'4.3 Industrialização 1930-1945',descricao:'- Tese de Furtado sobre recuperação pós-1933 como subproduto da defesa do setor cafeeiro (queima de estoques).'},
    {eixo:'4. História Econômica Brasileira',topico:'4.4 e 4.5 Década de 50 ao PAEG',descricao:'- Política econômica do governo Dutra (câmbio fixo, controle de importações, impactos na industrialização).'},
    {eixo:'4. História Econômica Brasileira',topico:'4.6 e 4.7 Milagre Econômico e II PND',descricao:'"- Políticas que favoreceram o ""milagre econômico"" e causas do endividamento externo nos anos 70."'},
    {eixo:'4. História Econômica Brasileira',topico:'4.8 e 4.9 Crise dos anos 80 e 90',descricao:'- Características da crise da dívida, reciclagem de petrodólares e formação do cartel de credores.'},
    {eixo:'Extras / Transversais',topico:'Demografia',descricao:'- Implicações da transição e do bônus demográfico para finanças públicas, poupança e mercado de trabalho no Brasil.'},
    {eixo:'Extras / Transversais',topico:'Conjuntura e Crises Globais',descricao:'- Impactos da retomada pós-Covid-19 na inflação e crescimento brasileiro.'},
    {eixo:'Extras / Transversais',topico:'Cadeias Globais de Valor (CGVs)',descricao:'- Determinantes da internacionalização da produção, subcontratação e desafio da inserção brasileira.'},
    {eixo:'Extras / Transversais',topico:'Energia e Meio Ambiente',descricao:'- Impacto das mudanças climáticas e alterações no mercado mundial de energia sobre a competitividade brasileira.'},
    {eixo:'Extras / Transversais',topico:'Metodologia de Preços',descricao:'- Discussão sobre mensuração do custo de vida verdadeiro frente a melhorias de qualidade em eletrônicos (ex.: DVDs).'},
    {eixo:'Extras / Transversais',topico:'Geopolítica',descricao:'- Impacto do financiamento da Guerra no Iraque e do déficit americano no investimento global.'}
  ],
  GEO: [
    {eixo:'1. História da Geografia',topico:'Correntes do pensamento geográfico tradicional',descricao:'Análise das correntes: determinismo, possibilismo e geografia regional.'},
    {eixo:'1. História da Geografia',topico:'Evolução do saber geográfico',descricao:'Conhecimentos antecedentes, determinismo, possibilismo, regionalismo, nova geografia, geografia crítica e abordagens fenomenológicas.'},
    {eixo:'1. História da Geografia',topico:'Abordagens espaciais e territoriais',descricao:'Fase inicial do determinismo, geografia crítica radical e geografia humanista.'},
    {eixo:'1. História da Geografia',topico:'Obra de Friedrich Ratzel',descricao:'Análise da obra de Ratzel sobre homogeneidade étnica em ilhas versus miscigenação em territórios abertos.'},
    {eixo:'2. A Geografia da População',topico:'Distribuição e Crescimento',descricao:'Causas da queda do crescimento populacional brasileiro, crescimento de cidades médias (750 a 50 mil hab.) e perda de população em municípios-sede de metrópoles.'},
    {eixo:'2. A Geografia da População',topico:'Migrações (século XXI)',descricao:'Fenômeno migratório no século XXI: refugiados, apátridas, redes de tráfico humano e o quadro da migração internacional no Brasil.'},
    {eixo:'2. A Geografia da População',topico:'Migrações (Brasil-Portugal)',descricao:'Imigração de brasileiros para Portugal: motivações, política de atração portuguesa e preferência por áreas metropolitanas.'},
    {eixo:'2. A Geografia da População',topico:'Migrações (Europa)',descricao:'Acordo de Schengen e o tratamento da imigração pelos países europeus em tempos de crise.'},
    {eixo:'2. A Geografia da População',topico:'Migrações (direitos humanos)',descricao:'Causas e fluxos das migrações internacionais globais e sua relação com os direitos humanos.'},
    {eixo:'2. A Geografia da População',topico:'Dinâmica e Estrutura (envelhecimento)',descricao:'O envelhecimento da população mundial e as perspectivas e desafios para a população idosa no Brasil.'},
    {eixo:'2. A Geografia da População',topico:'Dinâmica e Estrutura (China)',descricao:'Declínio da política do filho único na China: consequências históricas e impactos demográficos atuais.'},
    {eixo:'2. A Geografia da População',topico:'Dinâmica e Estrutura (Brasil)',descricao:'Transição demográfica no Brasil: alterações na estrutura etária e implicações socioeconômicas (Censo 2010).'},
    {eixo:'2. A Geografia da População',topico:'Qualidade de Vida',descricao:'Motivos da estabilização e crescimento da população rural em alguns países e suas potencialidades.'},
    {eixo:'3. Geografia Econômica',topico:'Globalização e DIT (chips)',descricao:'Reestruturação produtiva global, DIT no setor de chips e impactos da pandemia na produção de eletrônicos.'},
    {eixo:'3. Geografia Econômica',topico:'Globalização e DIT (ZPEs e offshore)',descricao:'Implicações das Zonas de Processamento de Exportações (ZPEs) e dos centros bancários offshore na economia globalizada.'},
    {eixo:'3. Geografia Econômica',topico:'Energia e Logística (portos e canais)',descricao:'Papel dos portos na globalização, importância da conteinerização e fragilidades de canais e estreitos geoestratégicos.'},
    {eixo:'3. Geografia Econômica',topico:'Energia e Logística (cabotagem)',descricao:'Navegação de cabotagem no Brasil: evolução histórica, aspectos favoráveis e dificuldades de desenvolvimento.'},
    {eixo:'3. Geografia Econômica',topico:'Energia e Logística (Custo Brasil)',descricao:'"Desafios da gestão do sistema de transportes no Brasil (rodoviário, ferroviário e hidroviário) e o ""Custo Brasil""."'},
    {eixo:'3. Geografia Econômica',topico:'Energia (matrizes e impactos)',descricao:'Matrizes energéticas atuais, formas espaciais associadas e impactos ambientais.'},
    {eixo:'3. Geografia Econômica',topico:'Energia (renováveis no Brasil)',descricao:'Opções de energias renováveis e não renováveis no Brasil e o eixo da futura matriz energética nacional.'},
    {eixo:'3. Geografia Econômica',topico:'Energia (hidro vs. termo)',descricao:'Quadro comparativo entre potencialidades da hidroeletricidade e da termoeletricidade no Brasil.'},
    {eixo:'3. Geografia Econômica',topico:'Energia (integração sul-americana)',descricao:'Integração energética sul-americana: fontes, sistemas de geração e relações existentes.'},
    {eixo:'3. Geografia Econômica',topico:'Reordenamento e Planejamento (pós-fordismo)',descricao:'Transformações pós-fordistas, espaços-de-fluxos vs. espaços-de-lugares e o papel do Estado Nacional e das fronteiras.'},
    {eixo:'3. Geografia Econômica',topico:'Reordenamento e Planejamento (Brasília)',descricao:'Transferência da capital para Brasília: redefinição das dinâmicas regionais e centralização espacial-financeira.'},
    {eixo:'3. Geografia Econômica',topico:'Reordenamento e Planejamento (DF)',descricao:'O Distrito Federal e Brasília: motivações da construção nacional-desenvolvimentista e avaliação dos objetivos atingidos.'},
    {eixo:'3. Geografia Econômica',topico:'Disparidades e Desenvolvimento (Nordeste)',descricao:'Dinâmicas econômicas na região Nordeste: atividades responsáveis pelo crescimento e fatores locais.'},
    {eixo:'3. Geografia Econômica',topico:'Disparidades e Desenvolvimento (China/Índia)',descricao:'Diferenças entre modelos de desenvolvimento e vantagens competitivas de China e Índia.'},
    {eixo:'3. Geografia Econômica',topico:'Disparidades e Desenvolvimento (África)',descricao:'África como nova fronteira de recursos minerais: atores envolvidos e implicações políticas.'},
    {eixo:'3. Geografia Econômica',topico:'Disparidades e Desenvolvimento (Ásia vs. América Latina)',descricao:'Diferenças no dinamismo econômico entre Ásia e América Latina nas últimas décadas.'},
    {eixo:'4. Geografia Agrária',topico:'Agronegócio (impactos)',descricao:'Impacto da expansão do agronegócio na perda de vegetação nativa, concentração fundiária e os desafios da agricultura familiar.'},
    {eixo:'4. Geografia Agrária',topico:'Agronegócio (RPAs)',descricao:'Regiões Produtivas do Agronegócio (RPAs): complexidade das regiões funcionais ao agronegócio globalizado e impactos na autonomia espacial.'},
    {eixo:'4. Geografia Agrária',topico:'Agronegócio (vantagens Brasil)',descricao:'A pujança do agronegócio brasileiro baseada em vantagens comparativas e competitivas.'},
    {eixo:'4. Geografia Agrária',topico:'Uso da Terra e Produção (cafeicultura)',descricao:'Histórico da cafeicultura em São Paulo: padrões de ocupação do solo e inovações em relação ao modelo colonial.'},
    {eixo:'4. Geografia Agrária',topico:'Uso da Terra e Produção (expansão)',descricao:'Percentual do território brasileiro destinado à agricultura e entraves para a expansão de terras agricultáveis.'},
    {eixo:'4. Geografia Agrária',topico:'Uso da Terra e Produção (país urbano)',descricao:'"Relação entre o peso dos produtos primários nas exportações e a imagem de ""país essencialmente urbano""."'},
    {eixo:'4. Geografia Agrária',topico:'Uso da Terra e Produção (manchas de fertilidade)',descricao:'Culturas agrícolas históricas e a exploração de manchas de fertilidade natural no solo brasileiro.'},
    {eixo:'5. Geografia Urbana',topico:'Urbanização e Redes (conceitos)',descricao:'Conceituação de rede urbana, tipologias de interações espaciais e a relação dialética da rede como realidade espacial.'},
    {eixo:'5. Geografia Urbana',topico:'Urbanização e Redes (Brasil)',descricao:'Evolução da rede urbana brasileira condicionada por processos econômico-sociais e a hierarquia das cidades do IBGE.'},
    {eixo:'5. Geografia Urbana',topico:'Metropolização e Conurbação (Grande SP)',descricao:'Dinâmica da Grande São Paulo: processos de urbanização, formação de periferias e fluxos/fixos metropolitanos.'},
    {eixo:'5. Geografia Urbana',topico:'Metropolização e Conurbação (segregação)',descricao:'Segregação socioespacial-intraurbana, enclaves fortificados e o direito à cidade.'},
    {eixo:'5. Geografia Urbana',topico:'Metropolização e Conurbação (globalização)',descricao:'Transformações da urbanização global e seu impacto na organização dos espaços intraurbanos brasileiros.'},
    {eixo:'5. Geografia Urbana',topico:'Cidades Médias (Amazônia)',descricao:'Papel das cidades médias na modernização do Brasil, especificamente na Amazônia e sua relação com redes fluviais e rodoviárias.'},
    {eixo:'5. Geografia Urbana',topico:'Cidades Médias (urbanização amazônica)',descricao:'Urbanização na Amazônia brasileira e a explicação para o elevado índice de população urbana na região.'},
    {eixo:'6. Geografia Política',topico:'Geopolítica e Poder (Mackinder)',descricao:'Teoria de Halford Mackinder aplicada à crise na Ucrânia e Crimeia e à geopolítica entre EUA/UE e Rússia.'},
    {eixo:'6. Geografia Política',topico:'Geopolítica e Poder (Grande Oriente Médio)',descricao:'"O projeto do ""Grande Oriente Médio"" dos EUA: área geográfica e dificuldades geopolíticas de implementação."'},
    {eixo:'6. Geografia Política',topico:'Geopolítica e Poder (energia)',descricao:'Tensões geopolíticas e visões de futuro energético em EUA, China e Rússia frente ao desenvolvimento sustentável.'},
    {eixo:'6. Geografia Política',topico:'Geopolítica e Poder (Turquia na UE)',descricao:'Geopolítica do ingresso da Turquia na União Europeia e as posições de Reino Unido, França e Alemanha.'},
    {eixo:'6. Geografia Política',topico:'Geopolítica e Poder (países ibéricos)',descricao:'"Estratégias políticas dos países ibéricos entre o ""atlantismo"" e o ""europeísmo""."'},
    {eixo:'6. Geografia Política',topico:'Geopolítica e Poder (Terceiro Mundo)',descricao:'"O conceito de ""Terceiro Mundo"": origens, apogeu e crise."'},
    {eixo:'6. Geografia Política',topico:'Estado e Território (frente pioneira)',descricao:'O conceito de frente pioneira na descrição da formação do território brasileiro e sua aplicabilidade atual.'},
    {eixo:'6. Geografia Política',topico:'Estado e Território (Amazônia)',descricao:'Geopolítica da Amazônia brasileira: movimentos sociais transnacionais e o desafio da soberania.'},
    {eixo:'6. Geografia Política',topico:'Estado e Território (Palestina)',descricao:'A proposta do Estado da Palestina e o óbice da demografia e dos refugiados.'},
    {eixo:'6. Geografia Política',topico:'Estado e Território (Sahel)',descricao:'Processo de secessão no Sahel africano e as questões geopolíticas de interface regional.'},
    {eixo:'6. Geografia Política',topico:'Fronteiras (Brasil)',descricao:'Contextos das fronteiras terrestres e litorâneas do Brasil: arcos de fronteira, zona costeira e possibilidades de desenvolvimento.'},
    {eixo:'6. Geografia Política',topico:'Fronteiras (aglomerações transfronteiriças)',descricao:'O papel das aglomerações transfronteiriças no desenvolvimento regional e na integração sul-americana.'},
    {eixo:'6. Geografia Política',topico:'Fronteiras (Sykes-Picot)',descricao:'O Acordo de Sykes-Picot e a partilha do Império Otomano: princípios geopolíticos da divisão de fronteiras.'},
    {eixo:'6. Geografia Política',topico:'Fronteiras (Amazônia Azul)',descricao:'"A ""Amazônia Azul"" e as implicações da nova fronteira marítima para a geopolítica brasileira no Atlântico Sul."'},
    {eixo:'7. Geografia e Gestão Ambiental',topico:'Questões Conceituais (desenvolvimento sustentável)',descricao:'O conceito de desenvolvimento sustentável como harmonização entre economia e ecologia e sua aplicação na Rio-92.'},
    {eixo:'7. Geografia e Gestão Ambiental',topico:'Questões Conceituais (biodiversidade)',descricao:'Implicações ambientais da biodiversidade brasileira frente ao desenvolvimento agrícola, industrial e energético.'},
    {eixo:'7. Geografia e Gestão Ambiental',topico:'Questões Conceituais (risco e vulnerabilidade)',descricao:'Risco, catástrofe e vulnerabilidade como elementos de produção social correlacionados à natureza e políticas.'},
    {eixo:'7. Geografia e Gestão Ambiental',topico:'Biomas e Domínios (domínios morfoclimáticos)',descricao:'Macrodivisão natural do Brasil através dos domínios morfoclimáticos (Ab\'Saber), características físicas e impactos ambientais.'},
    {eixo:'7. Geografia e Gestão Ambiental',topico:'Biomas e Domínios (queimadas)',descricao:'Impactos ambientais das queimadas nos biomas brasileiros e sul-americanos e suas consequências climáticas e sociais.'},
    {eixo:'7. Geografia e Gestão Ambiental',topico:'Biomas e Domínios (Cerrado)',descricao:'Valor estratégico dos recursos ambientais no Cerrado: segurança alimentar, suprimento de água e recursos genéticos.'},
    {eixo:'7. Geografia e Gestão Ambiental',topico:'Biomas e Domínios (zona costeira)',descricao:'Paisagens típicas e ecossistemas da zona costeira brasileira ao longo dos 7.500 km de litoral.'},
    {eixo:'7. Geografia e Gestão Ambiental',topico:'Biomas e Domínios (clima e vegetação)',descricao:'Correlação entre divisão climática e formações vegetais no Brasil e suas condições de conservação.'},
    {eixo:'7. Geografia e Gestão Ambiental',topico:'Biomas e Domínios (Caatinga)',descricao:'Biodiversidade da Caatinga: importância, proteção ambiental limitada e vetores de impacto antrópico.'},
    {eixo:'7. Geografia e Gestão Ambiental',topico:'Biomas e Domínios (Amazônia - patamares)',descricao:'Patamares orográficos da Amazônia e sistemas de exploração econômica associados.'},
    {eixo:'7. Geografia e Gestão Ambiental',topico:'Biomas e Domínios (tropicalidade e macrorregiões)',descricao:'Correlação entre a tropicalidade brasileira e a divisão oficial em macrorregiões do IBGE.'},
    {eixo:'7. Geografia e Gestão Ambiental',topico:'Política e Gestão (recursos hídricos)',descricao:'"A ""Questão da Água"" como problema geopolítico: escassez, aquíferos brasileiros e gestão de recursos hídricos."'},
    {eixo:'7. Geografia e Gestão Ambiental',topico:'Política e Gestão (política ambiental brasileira)',descricao:'Cronologia da política ambiental brasileira: concepções, etapas e instituições criadas.'},
    {eixo:'7. Geografia e Gestão Ambiental',topico:'Política e Gestão (agricultura e sustentabilidade)',descricao:'Gestão ambiental frente aos modelos agrícolas intensivos e a incorporação da sustentabilidade na agricultura.'},
    {eixo:'7. Geografia e Gestão Ambiental',topico:'Política e Gestão (Patrimônio Mundial UNESCO)',descricao:'Patrimônio Mundial da UNESCO no Brasil: relação entre preservação cultural/natural e desenvolvimento territorial histórico.'},
    {eixo:'7. Geografia e Gestão Ambiental',topico:'Política e Gestão (emissões e Rio-92)',descricao:'Realidade das emissões de gases poluentes e as discussões na Conferência Rio-92.'},
    {eixo:'8. Extras',topico:'Terceiro Mundo',descricao:'"Análise do conceito e evolução histórica do termo ""Terceiro Mundo"" no contexto geopolítico global."'}
  ],
  HB: [
    {eixo:'1. O Período Colonial',topico:'Configuração territorial (sécs. XVI-XVIII)',descricao:'Relação entre paradigma jurisdicionalista, organização do poder (capitanias, vilas e cidades) e mudanças nas práticas de territorialidade no século XVIII.'},
    {eixo:'1. O Período Colonial',topico:'Antecedentes territoriais',descricao:'Importância dos Tratados de Utrecht, resultados das negociações entre 1750 e 1801 e a ação de D. João VI na definição de fronteiras.'},
    {eixo:'1. O Período Colonial',topico:'Tratado de Madri (1750)',descricao:'Contribuição do negociador Alexandre de Gusmão e resultados para a demarcação do território brasileiro.'},
    {eixo:'2. O Processo de Independência',topico:'Contexto e projetos',descricao:'Influência do reformismo ilustrado (1808-1824), impacto da chegada da família real e a diversidade de projetos políticos regionais.'},
    {eixo:'2. O Processo de Independência',topico:'Dilemas políticos e sociais',descricao:'"Sentidos da transferência da Corte, conflitos armados no processo de separação, a ""invenção"" de uma nação liberal e os debates sobre a escravidão."'},
    {eixo:'2. O Processo de Independência',topico:'Período Joanino',descricao:'Transferência da Corte lusitana, medidas de interiorização da metrópole e panorama político entre Brasil e Portugal.'},
    {eixo:'2. O Processo de Independência',topico:'Independência em perspectiva',descricao:'Peculiaridade do processo de emancipação brasileiro frente à conjuntura internacional e aos movimentos da América hispânica.'},
    {eixo:'3. O Primeiro Reinado (1822-1831)',topico:'Vida político-institucional',descricao:'Relação entre herança colonial e ideias liberais, construção da Constituição de 1824, configurações jurídico-políticas e movimentos populares.'},
    {eixo:'3. O Primeiro Reinado (1822-1831)',topico:'Guerra Cisplatina',descricao:'Disputa de fronteira no Prata e consequências do conflito para a crise política e a abdicação de D. Pedro I.'},
    {eixo:'3. O Primeiro Reinado (1822-1831)',topico:'Reconhecimento da independência',descricao:'Análise das fases de José Bonifácio e da assinatura dos tratados com Portugal e Grã-Bretanha.'},
    {eixo:'3. O Primeiro Reinado (1822-1831)',topico:'Relações bilaterais (Inglaterra)',descricao:'A diplomacia entre Inglaterra e Brasil no período 1808-1831.'},
    {eixo:'3. O Primeiro Reinado (1822-1831)',topico:'Conformação estatal',descricao:'Raízes coloniais da política externa de D. Pedro I e resultados dos reconhecimentos internacionais na década de 1820.'},
    {eixo:'4. A Regência (1831-1840)',topico:'Reformas e disputas',descricao:'"As ""reformas liberais"" versus o ""regresso conservador"", centralização e descentralização, reformas institucionais e revoltas provinciais."'},
    {eixo:'4. A Regência (1831-1840)',topico:'Partidos políticos',descricao:'Pensamento político das correntes liberal e conservadora durante a Regência e início do Segundo Reinado e impacto na institucionalização do Estado.'},
    {eixo:'5. O Segundo Reinado (1840-1889)',topico:'Política externa e Prata',descricao:'"Motivações para a intervenção brasileira na navegação dos rios Amazonas, Paraná e Paraguai; Guerra do Paraguai, Tratado da Tríplice Aliança e atuação da diplomacia imperial."'},
    {eixo:'5. O Segundo Reinado (1840-1889)',topico:'Relações com a Inglaterra',descricao:'Pressão pelo fim do tráfico de escravos, herança lusitana na política externa e causas do rompimento/reatamento nas décadas de 1860 (Questão Christie).'},
    {eixo:'5. O Segundo Reinado (1840-1889)',topico:'Trabalho e Escravidão',descricao:'"O longo processo de abolição (1850-1888) e seus marcos legais; evolução das condições sociais e jurídicas do trabalho, da escravidão ao trabalho livre."'},
    {eixo:'5. O Segundo Reinado (1840-1889)',topico:'Crise e Intelectuais',descricao:'"Geração de 1870, circulação de ideias e crise do Estado Monárquico; construção da identidade nacional através do IHGB e da Academia Imperial de Belas Artes."'},
    {eixo:'5. O Segundo Reinado (1840-1889)',topico:'Sistema Eleitoral',descricao:'Análise das reformas eleitorais, fraudes, violência e o papel do Poder Moderador nas eleições do Império.'},
    {eixo:'5. O Segundo Reinado (1840-1889)',topico:'Diplomacia nas Repúblicas do Pacífico',descricao:'Política externa nas décadas de 1840/50 e a Missão Especial de Duarte da Ponte Ribeiro na Venezuela e Pacífico.'},
    {eixo:'5. O Segundo Reinado (1840-1889)',topico:'Relações Regionais (Argentina)',descricao:'As relações Brasil-Argentina nas três últimas décadas do século XIX.'},
    {eixo:'6. A Primeira República (1889-1930)',topico:'Política Externa e Rio Branco',descricao:'A obra do Barão do Rio Branco, arbitramentos de fronteiras (Guianas) e modernização da Chancelaria a partir de Campos Sales.'},
    {eixo:'6. A Primeira República (1889-1930)',topico:'Transformações estruturais',descricao:'"A ""aliança não escrita"" com os EUA, solução de fronteiras e os primeiros lances da diplomacia multilateral."'},
    {eixo:'6. A Primeira República (1889-1930)',topico:'Brasil e a Grande Guerra',descricao:'Posição brasileira na Primeira Guerra Mundial, fim da neutralidade em 1917 e participação na Conferência de Paz de Paris.'},
    {eixo:'6. A Primeira República (1889-1930)',topico:'Sociedade e Cultura',descricao:'Movimento Modernista, Semana de Arte Moderna de 1922 e os modernismos no Brasil.'},
    {eixo:'6. A Primeira República (1889-1930)',topico:'Instituições e Crises',descricao:'"Voto na Constituição de 1891, sistema eleitoral e cidadania; crise da década de 1920, Tenentismo e colapso da República Oligárquica."'},
    {eixo:'6. A Primeira República (1889-1930)',topico:'Economia',descricao:'Defesa das exportações, leis alfandegárias, imigração europeia e valorização do café.'},
    {eixo:'6. A Primeira República (1889-1930)',topico:'Transição e Proclamação',descricao:'Debates sobre o Manifesto Republicano e transformações ideológicas no final da Monarquia.'},
    {eixo:'6. A Primeira República (1889-1930)',topico:'Relações com EUA (Conferência de Washington 1889-1890)',descricao:'Comparação da posição brasileira entre Império e República.'},
    {eixo:'7. A Era Vargas (1930-1945)',topico:'Política e Economia',descricao:'"Análise geral do governo (1930-1945), ascensão e queda, política externa e econômica; Estado Novo (1937-45) e suas mudanças econômicas."'},
    {eixo:'7. A Era Vargas (1930-1945)',topico:'Crise do Estado Novo',descricao:'Movimento do Queremismo, diplomacia pendular, crise dos submarinos e entrada na Segunda Guerra Mundial.'},
    {eixo:'7. A Era Vargas (1930-1945)',topico:'Cultura',descricao:'Política cultural de Vargas, criação de órgãos estatais, controle da cultura popular e relação com intelectuais.'},
    {eixo:'7. A Era Vargas (1930-1945)',topico:'Movimentos Políticos',descricao:'Doutrina do Integralismo, AIB e sua relação de aproximação e posterior aniquilação pelo governo Vargas.'},
    {eixo:'7. A Era Vargas (1930-1945)',topico:'Capitalismo Nacional',descricao:'Iniciativas para a construção de uma via associada de capitalismo no Brasil na Era Vargas.'},
    {eixo:'8. A República Liberal (1945-1964)',topico:'Desenvolvimentismo e JK',descricao:'Política econômica de Juscelino Kubitschek, Plano de Metas, construção de Brasília e relações com o FMI.'},
    {eixo:'8. A República Liberal (1945-1964)',topico:'Política Externa Independente (PEI)',descricao:'Questão cubana na Conferência de Punta del Este (1962), descolonização afro-asiática e ideias de Araújo Castro.'},
    {eixo:'8. A República Liberal (1945-1964)',topico:'Relações com os EUA',descricao:'"Influência das modificações sistêmicas internacionais na política externa do governo Dutra; Comissão Mista Brasil-Estados Unidos na década de 1950."'},
    {eixo:'8. A República Liberal (1945-1964)',topico:'Crise e Colapso',descricao:'"Crise política de 1954; eleição e renúncia de Jânio Quadros; experiência da Constituição de 1946 e ruptura de 1964."'},
    {eixo:'8. A República Liberal (1945-1964)',topico:'Cultura e Pensamento',descricao:'Trajetória da diplomacia cultural, impacto do ISEB no pensamento político e repercussões na política externa.'},
    {eixo:'8. A República Liberal (1945-1964)',topico:'Missões Econômicas',descricao:'Dissertação sobre a Missão Abbink.'},
    {eixo:'9. O Regime Militar (1964-1985)',topico:'Política Externa',descricao:'"Relações com a Argentina (Castelo Branco e Geisel) e solução de contenciosos hídricos; setor energético no governo Geisel."'},
    {eixo:'9. O Regime Militar (1964-1985)',topico:'África e Descolonização',descricao:'Política para a África no governo Médici e o reconhecimento de Angola em 1975.'},
    {eixo:'9. O Regime Militar (1964-1985)',topico:'Estratégia e Segurança',descricao:'"Extensão do mar territorial para 200 milhas; inserção internacional de segurança entre 1945 e 1990."'},
    {eixo:'9. O Regime Militar (1964-1985)',topico:'Transição Política',descricao:'"Abertura ""lenta, gradual e segura"", impacto das eleições de 1974 e formação de oposição ao regime."'},
    {eixo:'10. O Processo Democrático a partir de 1985',topico:'Integração Regional',descricao:'Importância do MERCOSUL na agenda diplomática, Tratado de Assunção e cooperação com a Argentina.'},
    {eixo:'10. O Processo Democrático a partir de 1985',topico:'Redemocratização',descricao:'Processo de redemocratização na década de 1980, papel dos movimentos sociais, crise econômica e Constituição de 1988.'},
    {eixo:'10. O Processo Democrático a partir de 1985',topico:'Inserção Internacional',descricao:'Tema do desenvolvimento na inserção do Brasil e impacto da globalização na ação externa do Estado.'},
    {eixo:'10. O Processo Democrático a partir de 1985',topico:'Diplomacia no Cone Sul',descricao:'Política externa para a região nas décadas de 1980 e 1990.'},
    {eixo:'11. Impactos tecnológicos e digitais (Século XXI)',topico:'(Item do edital)',descricao:'Nenhuma questão discursiva no período 2003-2024 abordou especificamente este item.'},
    {eixo:'Extras (Questões de História Mundial ou Teoria)',topico:'Era das Revoluções',descricao:'Transformações socioeconômicas e políticas na Europa na transição do século XVIII para o XIX.'},
    {eixo:'Extras (Questões de História Mundial ou Teoria)',topico:'Orientalismo',descricao:'A produção de conhecimento sobre territórios extraeuropeus (Edward Said) e sua importância para a expansão europeia no século XIX.'}
  ]
};
